apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-rec-deployment
  namespace: facerec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-rec
  template:
    metadata:
      labels:
        app: face-rec
    spec:
      containers:
      - name: face-rec
        image: santoshburada/face_rec:latest
        ports:
        - containerPort: 8005
        envFrom:  # Use all keys in the secret as environment variables
        - secretRef:
            name: my-env-secret