apiVersion: v1
kind: Service
metadata:
  name: face-rec-service
  namespace: facerec
spec:
  type: NodePort
  ports:
  - port: 8005
    targetPort: 8005
    nodePort: 30005
  selector:
    app: face-rec