# don't forgot to create secret from .env
# kubectl create secret generic my-env-secret --from-env-file=.env
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crop-face-deployment
  namespace: facerec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crop-face
  template:
    metadata:
      labels:
        app: crop-face
    spec:
      containers:
      - name: crop-face
        image: santoshburada/crop_face:latest
        ports:
        - containerPort: 8001
        envFrom:  # Use all keys in the secret as environment variables
        - secretRef:
            name: my-env-secret
